source 'https://rubygems.org'
gem 'bourbon', '>= 4.0.2'
gem 'compass', '~> 1.0.1'
gem 'oily_png', '~> 1.1.1'
gem 'sass', '~> 3.4.3'
gem 'scss-lint', '~> 0.28'
gem 'sass-css-importer', '~> 1.0.0.beta.0'
